config/routes.rb
Rails.application.routes.draw do
  root 'pages#top'
  get    '/login', to: 'sessions#new' #ログインページの表示
  post   '/login', to: 'sessions#create' #ログイン処理
  delete '/logout', to: 'sessions#destroy' #ログアウト処理

  get    '/about', to: 'pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users # userに関するCRUDに必要なルーティングをすべて用意


  resources :tweets, only: [:create, :destroy, :new, :index]

  resources :tweets do
   resources :likes, only: [:create, :destroy]
  end

  # ここからフォロー
  post 'users/follow/:id',
       to: 'users#follow', as: 'follow'
  delete 'users/unfollow/:id',
         to: 'users#unfollow', as: 'unfollow'


  get 'users/:id/follow_list',
      to: 'users#follow_list',
      as: 'follow_list'

  get 'users/:id/follower_list',
      to: 'users#follower_list',
      as: 'follower_list'
end

# config/routes.rb
# rails info








# tweets/newページにアクセス。
# フォームに投稿内容を記述
# 投稿(submit)ボタンを押す→createアクションの実行

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :user_id, presence: true
  validates :tweet_id, presence: true
  validates :user_id, :uniqueness => {:scope => :tweet_id}

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy

  def like_user(user)
    likes.find_by(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, length: {maximum: 255}
  validates :password, presence: true, length: { minimum: 6 }
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy

  acts_as_follower
  acts_as_followable

  def liked_to(tweet)
    self.likes.find_by(tweet_id: tweet.id)
  end

  def following_tweets
    tweets = []
    self.all_following.each do |following_user| #配列！
      tweets.concat(following_user.tweets.last(10))
    end

    # Relation型に変換！
    Tweet.where(id: tweets.map{|tweet| tweet.id})
        .order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def logged_in?
    redirect_to login_url unless current_user
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  include SessionsHelper

  def create #いいねボタン
    @like = current_user.likes.create(tweet_id: params[:tweet_id])
    # redirect_to root_url

    @tweet = Tweet.find(params[:tweet_id])

    respond_to do |format| #指定された形式でレスポンスを返す
      format.html { redirect_to root_url } # いつも通りのhtml
      format.js # ajax通信用
    end
  end

  # views/likes/create.js.erb


  # current_user.likes.create()
  # like => user_id:current_user.id

  def destroy #いいね解除ボタン
    like = current_user.likes.find_by(tweet_id: params[:tweet_id])
    like.destroy
    # redirect_to root_url

    @tweet = Tweet.find(params[:tweet_id])

    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
  end
end

# destroy.js.erb

app/controllers/pages_controller.rb
## 静的ページを扱うコントローラー

class PagesController < ApplicationController
  include SessionsHelper
  before_action :logged_in?, only: :top

  def top
    @tweets = Tweet.all.order(created_at: :desc).page(params[:page]).per(5)
  end

  def about
  end

  private

    def logged_in?
      redirect_to login_url if current_user.nil?
    end
end


#views/pages/about.html.erb

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper #login, logout等実装

  def new #ログインページの描写
  end

  # フォーム入力値はparams[:session][:email], params[:session][:password]で取得できる！

  def create #ログイン処理
    user = User.find_by(email: params[:session][:email])

    if user && user.authenticate(params[:session][:password])
      # session[:user_id] = user.id
      log_in(user)
      redirect_to root_url

    else
      flash[:alert] = "メールアドレスもしくはパスワードが違います。"
      render 'new'
    end
  end

  # session[:user_id] = user.id

  def destroy #ログアウト処理
    logout
    redirect_to root_url
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  include SessionsHelper
  before_action :correct_user, only: :destroy


  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def index
    @tweets = current_user.following_tweets
                  .page(params[:page]).per(5)
  end

  # views/tweets/index.html.erb

  def destroy
    @tweet.destroy
    redirect_to root_url
  end

  private

    def tweet_params
      params.require(:tweet).permit(:content, :picture)
    end

    def correct_user # そのツイートは本当にあなたのもの？？
      @tweet = current_user.tweets.find_by(id: params[:id])
      redirect_to root_url if @tweet.nil?
    end

    def following_tweets(user)
      tweets = []
      user.all_following.each do |user|
        tweets.concat(user.tweets.last(10))
      end
      Tweet.where(id: tweets.map{|tweet| tweet.id})
          .order(created_at: :desc).page(params[:page]).per(5)
    end
end


# $ rails g controller tweets new

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  before_action :correct_user?, only: [ :edit, :update, :destroy ]

  def new
    @user = User.new #form_forメソッドに渡すため、空のユーザーオブジェクトの作成
  end

  def create
    @user = User.new(user_params)
    #①フォームに入力された値を取得し、
    #　それを元にユーザーオブジェクトを作成
    #②①で作られたユーザーオブジェクトをDBに保存する
    if @user.save
      # 成功した場合
      redirect_to root_url #トップページに戻る(redirect_toの際は_pathではなく_urlを用いる)
    else
      # 失敗した場合
      render 'new' #新規登録ページを描写(レンダリング)
    end
  end

  def edit
    @user = User.find(params[:id]) #URLのクエリパラメータからユーザーオブジェクトを取得
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params) #updateメソッドを用いて情報を更新
      #成功時
      redirect_to root_url
    else
      #失敗時
      render 'edit' #編集ページを描写(レンダリング)
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy #destroyメソッドを用いて削除
    redirect_to root_url
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.page(params[:page]).per(5) #ユーザーに紐づくツイートを取得。ツイート一覧パーシャルに引き渡す。
  end

  # app/views/users/show.html.erb


  ### ここからフォロー機能

  def follow #/users/follow/:id
    user = User.find(params[:id])
    current_user.follow(user) #フォローするメソッド
    redirect_to user_url(user)
  end

  def unfollow #/users/unfollow/:id
    user = User.find(params[:id])
    current_user.stop_following(user)
    redirect_to user_url(user)
  end

  ### フォローリストの描写

  def follow_list #( /users/:id/follow_list )
    @user = User.find(params[:id])
    @users = @user.all_following
  end

  # app/views/users/follow_list.html.erb

  def follower_list #( /users/:id/follower_list )
    @user = User.find(params[:id])
    @users = @user.followers
  end

  # app/views/users/follower_list.html.erb

  private

    def user_params #ストロングパラメータ 許可するパラメータを指定する。
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def correct_user?
      redirect_to root_url unless current_user == User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  #◯年◯月◯日
  
  def date_format(datetime)
    y = datetime.year
    m = datetime.month
    d = datetime.day
    
    return "#{y}年#{m}月#{d}日"
  end

  #created_at(datetime)を受け取り、
  #日本語の日付のフォーマット(文字列)に変換して返す

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
#(app/helpers/sessions_helper.rb)


module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def logout
    session.delete(:user_id)
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->

<!DOCTYPE html>
<html>
  <head>
    <title>TutoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css"
          href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag    'application',
                               media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'shared/header' %>

  <div class="main">

    <%= yield %>

  </div>




  </body>
</html>

app/views/likes/create.js.erb
$("#like_<%= @tweet.id %>").html("<%= escape_javascript(render 'pages/like', tweet: @tweet) %>");

app/views/likes/destroy.js.erb
$("#like_<%= @tweet.id %>").html("<%= escape_javascript(render 'pages/like', tweet: @tweet) %>");

app/views/pages/_like.html.erb
<% if current_user %>


  <% if tweet.like_user(current_user) %>

    <%= link_to tweet_like_path(tweet, tweet.like_user(current_user)), method: :delete, remote: true do %>

      <%= fa_icon 'heart', class: "fa-pink", text: tweet.likes.count %>

    <% end %>
  <% else %>

    <%= link_to tweet_likes_path(tweet), method: :post, remote: true do %>

      <%= fa_icon 'heart',  text: tweet.likes.count %>

    <% end %>

  <% end %>




<% else %>

  <%= fa_icon 'heart', text: tweet.likes.count %>

<% end %>

app/views/pages/top.html.erb
<%= render 'users/show_content', user: current_user %>


<div class="tweet-container">
  <div id="show-name">
    <ul id="show-list">
      <li style="font-weight: bold">新着ツイート一覧</li>
      <li><%= link_to "すべてのツイート", root_url %></li>
      <li><%= link_to "フォロー中", tweets_path %></li>
    </ul>
  </div>

  <%= link_to "すべてのツイート", root_url %>
  <%= link_to "フォロー中", tweets_path %>

  <%= render 'tweets/tweets', tweets: @tweets %>
</div>

app/views/shared/_header.html.erb
<header class="header">
  <div class="headerLeft">
    <h1 class="headerLogo"><%= link_to "TutoApp", root_url %></h1>
    <ul class="headerNav">
      <li><%= link_to "Home", root_url  %></li>
      <li><%= link_to "About", about_path %></li>
      <li>
        <% if current_user %>
          <%= link_to "つぶやく", new_tweet_path %>
        <% end %>
      </li>
    </ul>
  </div>

  <div class="headerRight">

    <div class="user_icon" style="background-image: url(<%= asset_path "dog.jpg" %>)"></div>

    <% if current_user %>

      <%= link_to current_user.name, user_path(current_user) %>
      <%#= current_user.name %>
      <%= link_to "ログアウト", logout_path, method: :delete %>

    <% else %>

      <%= link_to "新規登録", new_user_path %>
      <%= link_to "ログイン", login_path %>

    <% end %>

  </div>
</header>

app/views/tweets/_tweets.html.erb
<% tweets.each do |tweet| %>
  <div class="tweet">


    <div class="tweet-name">
      <%= link_to tweet.user.name, user_path(tweet.user) %>
    </div>

    <div class="tweet-content">
      <%= tweet.content %>
    </div>

    <div class="tweet-right" align="right">

      <span class="tweetDate">
        <%= date_format(tweet.created_at) %>
      </span>

      <!--  ここからいいね機能-->
      <span id="like_<%= tweet.id %>">

        <%= render 'pages/like', tweet: tweet %>

      </span>

    <!--  ここまでいいね機能-->







      <% if tweet.user == current_user %>
        <%= link_to "削除", tweet_path(tweet.id), method: :delete,
                  data: { confirm: "本当に削除しますか?" } %>
      <% end %>



    </div>

  </div>
<% end %>

<%= paginate tweets %>

app/views/tweets/index.html.erb
<div id="show-content">
  <div id="user-name">
    <%= current_user.name %>
  </div>
  <%= link_to "ユーザー情報編集", edit_user_path(current_user) %>

  <div id="follow_count">
    <%= link_to "follow(#{current_user.follow_count})", follow_list_path(current_user) %>
    <%= link_to "follower(#{current_user.followers_count})", follower_list_path(current_user) %>
  </div>
</div>


<div class="tweet-container">
  <div id="show-name">
    <ul id="show-list">
      <li style="font-weight: bold">新着ツイート一覧</li>
      <li><%= link_to "すべてのツイート", root_path %></li>
      <li><%= link_to "フォロー中", tweets_path %></li>
    </ul>
  </div>

  <%= render 'tweets/tweets', tweets: @tweets %>
</div>

app/views/tweets/new.html.erb
<div class="form-content">

  <% @tweet.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>

  <%= form_for(@tweet) do |f| %>
    <%= f.text_area :content, placeholder: "ツイートを入力して下さい" %>
    <%#= f.file_field :picture %>
    <%= f.submit "投稿する" %>
  <% end %>
</div>

app/views/users/_show_content.html.erb
<div id="show-content">
  <div id="user-name">
    <%= link_to user.name, user_path(user) %>
    <span class="edit-link"><%= link_to "編集", edit_user_path(current_user) if current_user == user %></span>
  </div>
  <% unless current_user == user %>

          <% if current_user.following? user %>
            フォロー中(<%= link_to 'ブロックする', unfollow_path(user), method: :delete %>)
          <% else %>
            <%= link_to 'フォローする', follow_path(user), method: :post %>
          <% end %>
  <% end %>

  <div id="follow_count">
    <%= link_to "follow(#{@user.follow_count})", follow_list_path(@user) %>
    <%= link_to "follower(#{@user.followers_count})", follower_list_path(@user) %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="form-content">
  <%= form_for(@user) do |f| %>

    <%= f.label :name, "ユーザー名" ,class: "label" %>
    <%= f.text_field :name %>

    <%= f.label :email, "メールアドレス" ,class: "label" %>
    <%= f.email_field :email %>

    <%= f.label :password, "パスワード" ,class: "label"%>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "パスワードの確認" ,class: "label" %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "アカウントを編集する" %>
  <% end %>
</div>

app/views/users/follow_list.html.erb
<div class="follow_list">

    <% @users.each do |user| %>
      <%= render 'show_content', user: user %>
    <% end %>

</div>

app/views/users/follower_list.html.erb
<div class="follow_list">

    <% @users.each do |user| %>
      <%= render 'show_content', user: user %>
    <% end %>

</div>

app/views/users/new.html.erb
<div class="form-content">


    <% @user.errors.full_messages.each do |message| %>
    <div class="error-message">
      <%= message %>
    </div>
    <% end %>


  <%= form_for(@user) do |f| %>

    <%= f.label :name, "ユーザー名", class: "label" %>
    <%= f.text_field :name %>

    <%= f.label :email, "メールアドレス", class: "label" %>
    <%= f.email_field :email %>

    <%= f.label :password, "パスワード", class: "label"%>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "パスワードの確認", class: "label" %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "アカウントを作成する" %>

  <% end %>
</div>

app/views/users/show.html.erb
<%= render 'show_content', user: @user %>

<div class="tweet-container">
  <div id="show-name">
  <%= @user.name %>さんのツイート一覧
  </div>

  <%= render 'tweets/tweets', tweets: @tweets %>
</div>
<%# unless @user == current_user %>
  <%# if current_user.following?(@user) %>
    <%#= link_to 'フォロー解除', unfollow_path(@user), method: :delete  %>
  <%# else %>
    <%#= link_to 'フォローする', follow_path(@user), method: :post %>
  <%# end %>
<%# end %>






<%#= @user.name %>
<%# if current_user && @user != current_user %>

  <%# if current_user.following?(@user) %>
    <%#= link_to 'フォロー解除', unfollow_path(@user), method: :delete  %>
  <%# else %>
    <%#= link_to 'フォローする', follow_path(@user), method: :post %>
  <%# end %>

<%# end %>

<%#= render 'tweets/tweets', tweets: @tweets  %>